
version: 2.1
      orbs:
  node: circleci/node@4.0.1
  parameter:
  app-dir:
  default: "~/project/sample"
workflows:
  test:
    jobs:
      - test
      jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: npm run test

