version: 2.1

orbs:
  node: circleci/node@3.0.0
  orb-tools: circleci/orb-tools@9.1

# Pipeline parameters
parameters:
  # These pipeline parameters are required by the "trigger-integration-tests-workflow"
  # job, by default.
  run-integration-tests:
    type: boolean
    default: false

integration-tests: &integration-tests
  [
    node-test-job,
    integration-test-override-ci,
    integration-test-yarn
  ]

executors:
  linux:
    docker:
      - image: cimg/base:stable
  macos:
    macos:
      xcode: 11.4

  integration-test-override-ci:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          override-ci-command: npm install
          cache-path: ~/project/node_modules
          cache-version: override-v3
          app-dir: "~/project/sample"
      - run: cd ~/project/sample && npm run test
  integration-test-yarn:
      executor: node/default
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: yarn
            cache-version: yarn-v3
            app-dir: "~/project/sample"
        - run: cd ~/project/sample && yarn test


workflows:
  # This `lint-pack_validate_publish-dev` workflow will run on any commit.
  lint_pack-validate_publish-dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      # pack your orb YAML files to a single orb.yml
      # validate the orb.yml file to ensure it is well-formed
      - orb-tools/pack

      - approve_for_testing:
          type: approval
          requires:
            - orb-tools/pack
            - orb-tools/lint

      # release dev version of orb, for testing & possible publishing.
      # orb will be published as dev:alpha and dev:${CIRCLE_SHA1:0:7}.
      # requires a CircleCI API token to be stored as CIRCLE_TOKEN (default)
      # https://circleci.com/docs/2.0/managing-api-tokens
      # store CIRCLE_TOKEN as a project env var or Contexts resource
      # if using Contexts, add your context below
      - orb-tools/publish-dev:
          orb-name: circleci/node
          context: orb-publishing
          requires:
            - approve_for_testing

      # trigger an integration workflow to test the
      # dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish-dev

  # This `integration-tests_prod-release` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-tests_prod-release:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - node/test:
          name: node-test-job
          app-dir: "~/project/sample"
          cache-version: v3
      - integration-test-override-ci
      - integration-test-yarn
