version: '2.1'
orbs:
  orb-tools: circleci/orb-tools@10
jobs:
  integration-tests-for-your-orb:
    executor: orb-tools/ubuntu
    steps:
      - checkout
workflows:
  integration-test_deploy:
    jobs:
      - integration-tests-for-your-orb
      - orb-tools/dev-promote-prod-from-commit-subject:
          add-pr-comment: false
          fail-if-semver-not-indicated: false
          filters:
            branches:
              only: master
          orb-name: your-namespace/your-orb
          publish-version-tag: false
          requires:
            - integration-tests-for-your-orb
    when: << pipeline.parameters.run-integration-tests >>
  test-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: your-namespace/your-orb-name
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
